# Generated by Django 4.2.1 on 2023-05-29 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(unique=True)),
                ('date_exp', models.DateField()),
                ('bank_type', models.CharField(max_length=20)),
                ('currency_type', models.CharField(max_length=20)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('pin', models.CharField(max_length=4)),
                ('associated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Banco_DB',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Destinatary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('associated_card', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': 'Destinatarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Electricity_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_id', models.IntegerField(unique=True)),
                ('electricity_cost', models.IntegerField()),
                ('propietary_name', models.CharField(max_length=50)),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Servicio_Electricidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Electricity_Service_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(unique=True)),
                ('propietary', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('import_service', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Pago_Electricidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gas_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_id', models.IntegerField(unique=True)),
                ('gas_cost', models.IntegerField()),
                ('propietary_name', models.CharField(max_length=50)),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Servicio_Gas ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gas_Service_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(unique=True)),
                ('propietary', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('import_service', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Pago_Gas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Person_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('date_birthday', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50, unique=True)),
                ('register', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Personas_DB',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Phone_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('propietary_name', models.CharField(max_length=50)),
                ('associated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Teléfonos_DB',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_card', models.IntegerField()),
                ('dest_card', models.IntegerField()),
                ('import_transfer', models.PositiveIntegerField()),
                ('confirm_mobile', models.IntegerField(null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=200, unique=True)),
                ('bank_type', models.CharField(max_length=20)),
                ('currency_type', models.CharField(max_length=20)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('pin', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['id'],
            },
        ),
    ]
