# Generated by Django 4.2.1 on 2023-05-17 21:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(unique=True)),
                ('date_exp', models.DateField()),
                ('bank_type', models.CharField(max_length=20)),
                ('currency_type', models.CharField(max_length=20)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('associated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Electricity_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_id', models.IntegerField(unique=True)),
                ('electricity_cost', models.IntegerField()),
                ('propietary_name', models.CharField(max_length=50)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gas_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_id', models.IntegerField(unique=True)),
                ('gas_cost', models.IntegerField()),
                ('propietary_name', models.CharField(max_length=50)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gener', models.CharField(max_length=50)),
                ('born_date', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('dni', models.IntegerField(unique=True)),
                ('register', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phone_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('propietary_name', models.CharField(max_length=50)),
                ('associated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_card', models.IntegerField()),
                ('dest_card', models.IntegerField()),
                ('import_transfer', models.PositiveIntegerField()),
                ('confirm_mobile', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=200, unique=True)),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.IntegerField(unique=True)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.person_db')),
            ],
        ),
        migrations.CreateModel(
            name='User_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=200, unique=True)),
                ('date_ex', models.DateField()),
                ('currency_type', models.CharField(max_length=20)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Gas_Service_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(unique=True)),
                ('propietary', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('import_service', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('id_gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.gas_service')),
            ],
        ),
        migrations.CreateModel(
            name='Electricity_Service_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(unique=True)),
                ('propietary', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('import_service', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('id_electricity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.electricity_service')),
            ],
        ),
        migrations.CreateModel(
            name='Destinatary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('associated_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.bank_db')),
            ],
        ),
    ]
