# Generated by Django 4.2.1 on 2023-05-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank_db',
            options={'ordering': ['id'], 'verbose_name': 'Banco_DB'},
        ),
        migrations.AlterModelOptions(
            name='destinatary',
            options={'ordering': ['id'], 'verbose_name': 'Destinatario', 'verbose_name_plural': 'Destinatarios'},
        ),
        migrations.AlterModelOptions(
            name='electricity_service',
            options={'ordering': ['id'], 'verbose_name': 'Servicio_Electricidad'},
        ),
        migrations.AlterModelOptions(
            name='electricity_service_pay',
            options={'ordering': ['id'], 'verbose_name': 'Pago_Electricidad'},
        ),
        migrations.AlterModelOptions(
            name='gas_service',
            options={'ordering': ['id'], 'verbose_name': 'Servicio_Gas '},
        ),
        migrations.AlterModelOptions(
            name='gas_service_pay',
            options={'ordering': ['id'], 'verbose_name': 'Pago_Gas'},
        ),
        migrations.AlterModelOptions(
            name='person_db',
            options={'ordering': ['id'], 'verbose_name': 'Personas_DB'},
        ),
        migrations.AlterModelOptions(
            name='phone_db',
            options={'ordering': ['id'], 'verbose_name': 'Teléfonos_DB'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['id'], 'verbose_name': 'Transferencia', 'verbose_name_plural': 'Transferencias'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.DeleteModel(
            name='User_Card',
        ),
    ]
