# Generated by Django 4.2.1 on 2023-05-22 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_id', models.IntegerField(unique=True)),
                ('electricity_cost', models.IntegerField()),
                ('propietary_name', models.CharField(max_length=50)),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Servicio_Electricidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gas_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_id', models.IntegerField(unique=True)),
                ('gas_cost', models.IntegerField()),
                ('propietary_name', models.CharField(max_length=50)),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Servicio_Gas ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_card', models.IntegerField()),
                ('dest_card', models.IntegerField()),
                ('import_transfer', models.PositiveIntegerField()),
                ('confirm_mobile', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gas_Service_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(unique=True)),
                ('propietary', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('import_service', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('id_gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.gas_service')),
            ],
            options={
                'verbose_name': 'Pago_Gas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Electricity_Service_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(unique=True)),
                ('propietary', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('import_service', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('id_electricity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.electricity_service')),
            ],
            options={
                'verbose_name': 'Pago_Electricidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Destinatary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('associated_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.bank_db')),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': 'Destinatarios',
                'ordering': ['id'],
            },
        ),
    ]
