# Generated by Django 4.2.1 on 2023-05-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_alter_bank_db_options_alter_destinatary_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=200, unique=True)),
                ('date_ex', models.DateField()),
                ('currency_type', models.CharField(max_length=20)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('pin', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.user')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='electricity_service_pay',
            name='id_electricity',
        ),
        migrations.RemoveField(
            model_name='gas_service_pay',
            name='id_gas',
        ),
        migrations.DeleteModel(
            name='Destinatary',
        ),
        migrations.DeleteModel(
            name='Electricity_Service_Pay',
        ),
        migrations.DeleteModel(
            name='Gas_Service_Pay',
        ),
    ]
