# Generated by Django 4.2.1 on 2023-05-31 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_main', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Electricity_Service_Pay',
            new_name='Service_Pay',
        ),
        migrations.AlterModelOptions(
            name='service_pay',
            options={'ordering': ['id'], 'verbose_name': 'Pago_Servicio'},
        ),
        migrations.AlterField(
            model_name='user_card',
            name='card_number',
            field=models.IntegerField(unique=True),
        ),
    ]
