# Generated by Django 4.2.1 on 2023-05-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_rename_electricity_service_pay_service_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='import_transfer',
            field=models.IntegerField(),
        ),
    ]
