# Generated by Django 4.2.1 on 2023-05-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_user_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_card',
            name='user',
        ),
        migrations.AlterField(
            model_name='user_card',
            name='card_number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_card',
            name='currency_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_card',
            name='date_ex',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user_card',
            name='pin',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
