# Generated by Django 4.2.1 on 2023-06-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_transfer_import_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='confirm_mobile',
        ),
        migrations.AlterField(
            model_name='destinatary',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
