# Generated by Django 4.2.1 on 2023-05-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_remove_user_card_user_alter_user_card_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_db',
            name='pin',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
