# Generated by Django 4.2.1 on 2023-05-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_bank_db_pin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank_DB',
        ),
        migrations.DeleteModel(
            name='Electricity_Service',
        ),
        migrations.DeleteModel(
            name='Gas_Service',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.DeleteModel(
            name='User_Card',
        ),
    ]
