# Generated by Django 4.2.1 on 2023-05-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_delete_bank_db_delete_electricity_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(unique=True)),
                ('date_exp', models.DateField()),
                ('bank_type', models.CharField(max_length=20)),
                ('currency_type', models.CharField(max_length=20)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('pin', models.CharField(max_length=4)),
                ('associated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Banco_DB',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=200, unique=True)),
                ('date_ex', models.DateField()),
                ('currency_type', models.CharField(max_length=20)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('pin', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['id'],
            },
        ),
    ]
